compute_environment: LOCAL_MACHINE
debug: false
distributed_type: MULTI_GPU
fsdp_config:
  fsdp_version: 2
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
main_training_function: main
mixed_precision: 'bf16'
dynamo_config:
  dynamo_backend: 'inductor'
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
use_cpu: false